# This is a config for E2B sandbox template.
# You can use template ID (lzzg8arjmre0bygc4iif) or template name (vibe-nextjs-heeseong-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-heeseong-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-heeseong-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-heeseong-2')

team_id = "c7eb39aa-199e-45be-89f9-2e768c4f43b5"
start_cmd = "./compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-heeseong-2"
template_id = "lzzg8arjmre0bygc4iif"
